# Generated by Django 4.2.27 on 2026-01-31 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('percent_discount', models.PositiveIntegerField(verbose_name='Phần trăm giảm giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Hãng sản xuất')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Ảnh chính')),
                ('description', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('specifications', models.TextField(verbose_name='Thông số kỹ thuật')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gốc')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá khuyến mãi')),
                ('discount_percent', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Phần trăm giảm giá (%)')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='Thời gian bảo hành (tháng)')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Miễn phí vận chuyển')),
                ('open_box_check', models.BooleanField(default=False, verbose_name='Mở hộp kiểm tra')),
                ('return_30_days', models.BooleanField(default=False, verbose_name='Đổi trả trong 30 ngày')),
                ('youtube_id', models.CharField(blank=True, max_length=50, verbose_name='ID Video YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=50, verbose_name='Dung lượng bộ nhớ')),
                ('original_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá gốc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_options', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tùy chọn bộ nhớ',
                'verbose_name_plural': 'Tùy chọn bộ nhớ',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Hình ảnh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh chi tiết',
                'verbose_name_plural': 'Hình ảnh chi tiết',
            },
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='Tên màu')),
                ('color_image', models.ImageField(upload_to='products/colors/', verbose_name='Hình ảnh màu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tùy chọn màu sắc',
                'verbose_name_plural': 'Tùy chọn màu sắc',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Đánh giá')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
