# Generated by Django 4.2.27 on 2026-01-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20260131_2205'),
    ]

    operations = [
    ]
