# Generated by Django 4.2.27 on 2026-01-31 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_add_order_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('processing', 'Tiếp nhận'), ('completed', 'Thành công'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('online', 'Thanh toán online')], default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền hàng')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Mã giảm giá')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='percent_discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Giảm theo phần trăm'), ('fixed', 'Giảm số tiền cố định')], default='percent', max_length=10, verbose_name='Loại giảm giá'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Giá trị giảm'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.PositiveIntegerField(default=0, help_text='Áp dụng cho loại giảm phần trăm. 0 = không giới hạn.', verbose_name='Giảm tối đa (VND)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Đơn hàng tối thiểu (VND)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='Tên sản phẩm')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='Bộ nhớ')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu sắc')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Sản phẩm trong đơn hàng',
            },
        ),
    ]
