# Generated by Django 4.2.27 on 2026-01-31 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_userprofile_is_phone_verified_uservoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Góp ý',
                'verbose_name_plural': 'Góp ý',
                'ordering': ['-created_at'],
            },
        ),
    ]
