# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Đã đánh giá'),
        ),
    ]

