# Generated by Django 4.2.27 on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderitem_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Đánh giá ẩn danh'),
        ),
    ]

